/** Figma assets — exported to public/assets/figma (see scripts/download-figma-assets.mjs) */
const BASE = '/assets/figma';

export const figmaAssets = {
  mapBackground: `${BASE}/map-background.png`,
  layersIcon: `${BASE}/layers.svg`,
  /** כפתור שכבת תחקירים על המפה — מילוי כמו layers.svg */
  tahkirLayersIcon: `${BASE}/tahkir-layers-icon.svg`,
  toolsIcon: `${BASE}/tools.svg`,
  missionPlanBg: `${BASE}/mission-plan-bg.svg`,
  missionPlanChevron: `${BASE}/mission-plan-chevron.svg`,
  missionTarget: `${BASE}/mission-target.svg`,
  /** Mission Plan dropdown 312:145182 */
  mpIconPerson: `${BASE}/mp-icon-person.svg`,
  mpIconAir: `${BASE}/mp-icon-air.svg`,
  mpIconSword: `${BASE}/mp-icon-sword.svg`,
  mpIconElectricity: `${BASE}/mp-icon-electricity.svg`,
  mpIconShield: `${BASE}/mp-icon-shield.svg`,
  mpIconAgam: `${BASE}/mp-icon-agam.svg`,
  mpRowGlow: `${BASE}/mp-row-glow.svg`,
  userCardBg: `${BASE}/user-card-bg.svg`,
  /** User 719:27213 — Rectangle 454 */
  userCardBgV2: `${BASE}/user-card-bg-v2.svg`,
  userChevronBadge: `${BASE}/user-chevron-badge.svg`,
  userChevronBadgeV2: `${BASE}/user-chevron-badge-v2.svg`,
  userChevron: `${BASE}/user-chevron.svg`,
  userChevronV2: `${BASE}/user-chevron-v2.svg`,
  userEmblemBg: `${BASE}/user-emblem-bg.svg`,
  userEmblemBgV2: `${BASE}/user-emblem-bg-v2.svg`,
  userEmblem: `${BASE}/user-emblem.png`,
  userEmblemV2: `${BASE}/user-emblem-v2.png`,
  searchIcon: `${BASE}/search.svg`,
  headerBg: `${BASE}/header-bg.svg`,
  /** Side bar 719:27607 — חשיפה תקיפה */
  sidebarRailBg: `${BASE}/sidebar-rail-bg.svg`,
  sideMenuMissionIcon: `${BASE}/side-menu-mission-icon.svg`,
  /** Folded map / atlas glyph — used for the main tactical map nav item */
  sideMenuMapIcon: `${BASE}/side-menu-mission.svg`,
  sideMenuAreaIcon: `${BASE}/side-menu-area-icon.svg`,
  sideMenuJournalIcon: `${BASE}/side-menu-journal-icon.svg`,
  sideMenuGuardIcon: `${BASE}/side-menu-guard-icon.svg`,
  /** Figma 393:36731 — עץ ציוות */
  sideMenuCrewTreeIcon: `${BASE}/side-menu-crew-tree.svg`,
  /** Figma 392:30648 — תחקיר (layout-list) */
  sideMenuTahkirIcon: `${BASE}/side-menu-tahkir.svg`,
  /** אג"ם — Figma 719:27752 */
  agamBattlePictureIcon: `${BASE}/agam-battle-picture.svg`,
  agamEffortSyncIcon: `${BASE}/agam-effort-sync.svg`,
  agamTamachIcon: `${BASE}/agam-tamach.svg`,
  agamPlanManagementIcon: `${BASE}/agam-plan-management.svg`,
  agamPermissionsIcon: `${BASE}/agam-permissions.svg`,
  /** תקשוב — מיפוי סמנטי לפי כותרת (PRD_ICT §מיפוי אייקונים) */
  ictNavDashboard: `${BASE}/ict-nav-dashboard.svg`,
  ictNavPlanning: `${BASE}/ict-nav-planning.svg`,
  ictNavSync: `${BASE}/ict-nav-sync.svg`,
  ictNavRadio: `${BASE}/ict-nav-radio.svg`,
  ictNavSpectrum: `${BASE}/ict-nav-spectrum.svg`,
  ictNavMonitor: `${BASE}/ict-nav-monitor.svg`,
  ictNavCrewSupport: `${BASE}/ict-nav-crew-support.svg`,
  ictNavLomer: `${BASE}/ict-nav-lomer.svg`,
  ictNavManhala: `${BASE}/ict-nav-manhala.svg`,
  /** פקמ"ב — file-text (Figma 392 ecosystem) */
  sideMenuPkmbIcon: `${BASE}/side-menu-pkmb.svg`,
  tahkirTimelineIcon: `${BASE}/tahkir-timeline-icon.svg`,
  tahkirCreateIcon: `${BASE}/tahkir-create-icon.svg`,
  tahkirPlay: `${BASE}/tahkir-play.svg`,
  tahkirFastForward: `${BASE}/tahkir-fast-forward.svg`,
  tahkirCalendarIcon: `${BASE}/tahkir-calendar-2.svg`,
  /** Figma 393:34791 — תחקור מרחב */
  tahkirSpaceIcon: `${BASE}/tahkir-space-icon.svg`,
  tahkirRecVideo: `${BASE}/tahkir-rec-video.svg`,
  tahkirRecUpload: `${BASE}/tahkir-rec-upload.svg`,
  tahkirRecPhone: `${BASE}/tahkir-rec-phone.svg`,
  tahkirDiaryDot: `${BASE}/tahkir-diary-dot.svg`,
  tahkirDiaryLine: `${BASE}/tahkir-diary-line.svg`,
  sideDocChat: `${BASE}/side-doc-chat.svg`,
  sideDocPlus: `${BASE}/side-doc-plus.svg`,
  sideDocVideo1: `${BASE}/side-doc-video-1.svg`,
  sideDocVideo2: `${BASE}/side-doc-video-2.svg`,
  sideAiIcon: `${BASE}/side-ai-icon.svg`,
  wifi1: `${BASE}/wifi-1.svg`,
  wifi2: `${BASE}/wifi-2.svg`,
  wifi3: `${BASE}/wifi-3.svg`,
  layoutIcon: `${BASE}/layout.svg`,
  applicationsIcon: `${BASE}/applications.svg`,
  notificationBell: `${BASE}/notification-bell.svg`,
  notificationDot: `${BASE}/notification-dot.svg`,
  settingsIcon: `${BASE}/settings.svg`,
  helpIcon: `${BASE}/help.svg`,
  compassSnap: `${BASE}/compass-snap.svg`,
  compassDial: `${BASE}/compass-dial.svg`,
  compassNeedle: `${BASE}/compass-needle.svg`,
  compassZoomOuter: `${BASE}/compass-zoom-outer.svg`,
  compassZoomInner: `${BASE}/compass-zoom-inner.svg`,
  compassMinus: `${BASE}/compass-minus.svg`,
  compassPlus: `${BASE}/compass-plus.svg`,
  footerScale: `${BASE}/footer-scale.svg`,
  missionMinilist: `${BASE}/mission-minilist.svg`,
  /** Sidebar toggle — Figma 393:34619 */
  sidebarToggleBg: `${BASE}/sidebar-toggle-bg.svg`,
  sidebarToggleHighlight: `${BASE}/sidebar-toggle-highlight.svg`,
  sidebarToggleChevron: `${BASE}/sidebar-toggle-chevron.svg`,
  sidebarToggleIcon: `${BASE}/sidebar-toggle-icon.svg`,
  menuIcon: `${BASE}/menu.svg`,
  actionTopBg: `${BASE}/action-top-bg.svg`,
  actionMidBg: `${BASE}/action-mid-bg.svg`,
  actionBottomBg: `${BASE}/action-bottom-bg.svg`,
  actionTechIcon: `${BASE}/action-tech.svg`,
  actionMapIcon: `${BASE}/action-map.svg`,
} as const;
